import test, { expect } from '@playwright/test'
test('Assertion and locator', async ({ page }) => {
    await page.goto("http://leaftaps.com/opentaps/control/main")
    await page.getByLabel("Username").fill("Demosalesmanager")
    await page.getByLabel("Password").fill("crmsfa")
    await page.getByRole('button', { name: 'Login' }).click()
    await page.getByText("CRM/SFA").click()
    await page.getByRole('link', { name: 'Leads' }).click()
    await page.getByText("Create Lead").click()
    await page.locator("#createLeadForm_companyName").fill("Testleaf")
    await page.locator("#createLeadForm_firstName").fill("sangirthiayayan")
    await page.locator("#createLeadForm_lastName").fill("c")
    await page.locator("[name='personalTitle']").fill("Mr.")
    await page.locator("[name='generalProfTitle']").fill("Tester")
    await page.locator("[name='annualRevenue']").fill("90000")
    await page.locator("[name='departmentName']").fill("Playwright")
    await page.locator("#createLeadForm_primaryPhoneNumber").fill("657676986998n")
    await page.locator(".smallSubmit").click()
    const store1 = await page.locator("#viewLead_firstName_sp")
    const store2 = await page.locator("#viewLead_lastName_sp")
    const store3 = await page.locator("//span[contains(text(),'Testleaf ')]")
    await expect(store3).toContainText("Testleaf")
    await expect(store1).toHaveText("sangirthiyayan")
    await expect(store2).toHaveText("c")
    const status = await page.locator("#viewLead_statusId_sp").innerText()
    const whiteSpace = status?.trim()
    expect(whiteSpace).toBe("Assigned")

})